#server.port=8090

#是否将自己注册到Eureka Server，默认为true，由于当前就是server，故而设置成false
#表明该服务不会向eureka注册自己的信息
#eureka.client.register-with-eureka=false
#是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
#eureka.client.fetch-registry=false
#设置服务注册中心的URL，用于client和server端交流
#eureka.client.service-url.defaultZone=http://localhost:7900/eureka/

spring:
  application:
    name: eureka-server

---
#springboot2.4配置，spring.profiles已废弃，用如下代替
spring:
  config:
    activate:
      on-profile: euk2

eureka:
  instance:
    hostname: euk2.com
  client:
    service-url:
      defaultZone: http://euk1.com:7001/eureka/

server:
  port: 7002

---

spring:
  config:
    activate:
      on-profile: euk1
eureka:
  instance:
    hostname: euk1.com
  client:
    service-url:
      defaultZone: http://euk2.com:7002/eureka/

server:
  port: 7001